### PR TITLE
Replace deprecated ::Fixnum with ::Integer

### LINKED ISSUE #10: Deprecation warnings on Ruby 2.4
`warning: constant ::Fixnum is deprecated`

### PR DESCRIPTION
**Pull request by goodmike**
[ Closes #10 ]

### CODE REVIEW

**Comment by mbj** [comment]
Code wise I like this, but the CI integration is broken, have to fix that one first and re-build it.

**Comment by goodmike** [comment]
I noticed that the [PR that addresses this issue in `devtools`](https://github.com/goodmike/devtools/commit/c6732d0936578226ea6b8149e50c6bfba23de923) replaces the `Fixnum` constant with `0.class`. Would you prefer that?

**Comment by mbj** [comment]
@goodmike I do not think this is required here.

**Comment by mbj** [comment]
Redundant with #12

**Pull request closed without merging**
